# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0.0)),
                ('volume', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('index_weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='StockIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='equity',
            name='stockindex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockindex.StockIndex'),
        ),
    ]
