# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='stockindex',
            name='description',
        ),
    ]
