# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockindex', '0002_auto_20160326_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='index_weight',
        ),
    ]
